### ISSUE TITLE
unused arguments (old_school = FALSE, sidebar_min = TRUE, sidebar_collapsed = FALSE, controlbar_collapsed = TRUE, controlbar_overlay = TRUE)

### ISSUE THREAD

**Issue by hpbenton** [pcastellanoescuder/POMA_Shiny#2]
When building the docker image manually or running the Shiny app locally  I get the following error 

`unused arguments (old_school = FALSE, sidebar_min = TRUE, sidebar_collapsed = FALSE, controlbar_collapsed = TRUE, controlbar_overlay = TRUE)`

**Comment by pcastellanoescuder** [comment]
Hey @hpbenton! Thanks for reporting!

This is not a POMAShiny problem but a `bs4Dash` issue. POMAShiny was built using `bs4Dash` version 0.5.0 and is not compatible with newer versions of `bs4Dash` due to substantial breaking changes in the API. 

As indicated by the `bs4Dash` developers, it's better to keep using the old version of `bs4Dash`. This has been updated in the Dockerfile and in the README installation instructions.
